# Generated by Django 4.2.3 on 2023-07-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F')),
                ('age', models.CharField(choices=[('C', 'Child'), ('T', 'Teen'), ('A', 'Adult')], default='T')),
                ('price', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, upload_to='clothes/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.brand')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.type')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='distributor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.distributor'),
        ),
    ]
