# Generated by Django 4.2.3 on 2023-07-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
