# Generated by Django 4.2.3 on 2023-07-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Type_Clothe',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='type',
            new_name='type_clothe',
        ),
    ]
