# Generated by Django 4.2.3 on 2023-08-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_rename_type_type_clothe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large')])),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='clothes.sizes'),
        ),
    ]
