# Generated by Django 4.2.3 on 2023-08-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_sizes_clothes_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='clothes.sizes'),
        ),
        migrations.CreateModel(
            name='Clothe_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='clothes/')),
                ('color', models.ManyToManyField(blank=True, to='clothes.colors')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='clothes.clothe_image'),
        ),
    ]
