# Generated by Django 4.2.3 on 2023-08-02 04:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_colors_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
