# Generated by Django 4.2.3 on 2023-08-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_brand_options_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(null=True, upload_to='clothes_media/'),
        ),
    ]
