# Generated by Django 4.2.3 on 2023-09-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_alter_clothes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='image_for_clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothes_media/')),
            ],
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='clothes.brand'),
        ),
        migrations.CreateModel(
            name='image_and_color_of_clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloteh_image', models.ManyToManyField(to='clothes.image_for_clothe')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.colors')),
            ],
        ),
    ]
