# Generated by Django 4.2.3 on 2023-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_rename_cloteh_image_image_and_color_of_clothe_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
        migrations.AddField(
            model_name='clothes',
            name='ColorImages',
            field=models.ManyToManyField(to='clothes.image_and_color_of_clothe'),
        ),
    ]
