# Generated by Django 4.2.3 on 2023-10-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_remove_clothes_color_remove_clothes_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand_2',
        ),
    ]
