# Generated by Django 4.2.3 on 2023-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_clothe',
            name='color',
            field=models.CharField(default='black'),
        ),
        migrations.AddField(
            model_name='order_clothe',
            name='color_value',
            field=models.CharField(default='#000000'),
        ),
    ]
