# Generated by Django 4.2.3 on 2023-08-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_brand_options_alter_clothes_options_and_more'),
        ('car_shop', '0002_order_clothe_color_order_clothe_color_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_clothe',
            name='color_value',
        ),
        migrations.AlterField(
            model_name='order_clothe',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.colors'),
        ),
    ]
