# Generated by Django 4.2.3 on 2023-08-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_brand_options_alter_clothes_options_and_more'),
        ('car_shop', '0003_remove_order_clothe_color_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_clothe',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.sizes'),
        ),
    ]
