version: '3'
services:
  simple-store:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    
    
    ports: 
      - 7000:8000
    
    command: bash -c "gunicorn Simple_Store_D.wsgi:application --bind 0.0.0.0:8000" 

    depends_on:
      - postgresql


    environment:
      - SIMPLE_STORE_DATABASE_HOSTNAME=${SIMPLE_STORE_DATABASE_HOSTNAME}
      - SIMPLE_STORE_DATABASE_PORT=${SIMPLE_STORE_DATABASE_PORT}
      - SIMPLE_STORE_DATABASE_PASSWORD=${SIMPLE_STORE_DATABASE_PASSWORD}
      - SIMPLE_STORE_DATABASE_USERNAME=${SIMPLE_STORE_DATABASE_USERNAME}
      - SIMPLE_STORE_DATABASE_NAME=${SIMPLE_STORE_DATABASE_NAME}
      - SIMPLE_STORE_SECRET_KEY=${SIMPLE_STORE_SECRET_KEY}
      - SIMPLE_STORE_DEFAULT_EMAIL=${SIMPLE_STORE_DEFAULT_EMAIL}
      - SIMPLE_STORE_DEFAULT_PASSWORD=${SIMPLE_STORE_DEFAULT_PASSWORD}
      - SIMPLE_STORE_EMAIL=${SIMPLE_STORE_EMAIL}
      - SIMPLE_STORE_PASSWORD=${SIMPLE_STORE_PASSWORD}
       

  postgresql:
    image: postgres 
    ports:
      - 5434:5432
    
    environment:
      - POSTGRES_PASSWORD=${SIMPLE_STORE_DATABASE_PASSWORD}
      - POSTGRES_DB=${SIMPLE_STORE_DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
  postgres-db: