version: '3.8'

services:
  simple-store:
    build: 
      context: .
      dockerfile: Dockerfile.prod

    command: bash -c "gunicorn Simple_Store_D.wsgi:application --bind 0.0.0.0:8000" 
    
    volumes: 
      - static_volume:/home/Simple_Store_D/web/static
      - media_volume:/home/Simple_Store_D/web/media

    expose: 
      - 8000 
    
    environment:
      - SIMPLE_STORE_DATABASE_HOSTNAME=${SIMPLE_STORE_DATABASE_HOSTNAME}
      - SIMPLE_STORE_DATABASE_PORT=${SIMPLE_STORE_DATABASE_PORT}
      - SIMPLE_STORE_DATABASE_PASSWORD=${SIMPLE_STORE_DATABASE_PASSWORD}
      - SIMPLE_STORE_DATABASE_USERNAME=${SIMPLE_STORE_DATABASE_USERNAME}
      - SIMPLE_STORE_DATABASE_NAME=${SIMPLE_STORE_DATABASE_NAME}
      - SIMPLE_STORE_SECRET_KEY=${SIMPLE_STORE_SECRET_KEY}
      - SIMPLE_STORE_DEFAULT_EMAIL=${SIMPLE_STORE_DEFAULT_EMAIL}
      - SIMPLE_STORE_DEFAULT_PASSWORD=${SIMPLE_STORE_DEFAULT_PASSWORD}
      - SIMPLE_STORE_EMAIL=${SIMPLE_STORE_EMAIL}
      - SIMPLE_STORE_PASSWORD=${SIMPLE_STORE_PASSWORD}
       
    depends_on:
      - postgresql 

  postgresql:
    image: postgres

    ports:
      - 5434:5432
    
    environment:
      - SIMPLE_STORE_POSTGRES_PASSWORD=${SIMPLE_STORE_DATABASE_PASSWORD}
      - POSTGRES_DB=${SIMPLE_STORE_DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data
    
  nginx:
    build: ./nginx 
    
    volumes:
      - static_volume:/home/Simple_Store_D/web/static
      - media_volume:/home/Simple_Store_D/web/media
    
    ports:
      - 8001:80 
    
    depends_on:
      - simple-store
  
volumes:
  postgres-db:
  static_volume: 
  media_volume: 
    