"""
Django settings for Simple_Store_D project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
#Images sizes i need (1320,583)

from pathlib import Path
from .config import settings_core
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings_core.simple_store_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["localhost",'127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'Simple_Store_D.apps.MyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "clothes",
    "car_shop",
    "user_settings",
    "colorfield",
    'django_middleware_global_request',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_middleware_global_request.middleware.GlobalRequestMiddleware',
]

ROOT_URLCONF = 'Simple_Store_D.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Simple_Store_D.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': settings_core.simple_store_database_name,
        "USER": settings_core.simple_store_database_username,
        "PASSWORD": settings_core.simple_store_database_password,
        "HOST": settings_core.simple_store_database_hostname,
        "PORT" : settings_core.simple_store_database_port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR,"static/")
STATIC_URL = "/static/"


MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR,"media")
MEDIA_TEST = os.path.join(MEDIA_ROOT,"resized/")
if not os.path.isdir(MEDIA_ROOT):
    os.mkdir(MEDIA_ROOT)

if not os.path.isdir(MEDIA_TEST):
    os.mkdir(MEDIA_TEST)
    
if not os.path.isdir(STATIC_ROOT):
    os.mkdir(STATIC_ROOT)
    
media_dir = os.path.join(MEDIA_ROOT,"clothes_media/")

if not os.path.isdir(media_dir):
    os.mkdir(media_dir)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"

EMAIL_USE_TLS = True 

EMAIL_PORT = 587
EMAIL_HOST_USER = settings_core.simple_store_email
EMAIL_HOST_PASSWORD = settings_core.simple_store_password

CSRF_TRUSTED_ORIGINS = ["http://localhost:8001"]

